# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Action Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install tweepy
          pip install google-api-core
          pip install google-auth
          pip install google-cloud-language==1.0.0
      - name: Test with pytest
        env:
          consumer_key: ${{secret.consumer_key}}
          consumer_secret: ${{secret.consumer_secret}}
          access_key: ${{secret.access_key}}
          access_secret: ${{secret.access_secret}}
        run: |
          pytest
